### ISSUE TITLE
ERROR: tensorflow_macos-0.1a0-cp38-cp38-macosx_11_0_arm64.whl is not a supported wheel on this platform.

### ISSUE THREAD

**Issue by oresttokovenko** [mwidjaja1/DSOnMacARM#3]
First of all thank you for the code! I got the end of the install and it said `Successfully built wrapt
Installing collected packages: wrapt, tensorflow-estimator, keras-preprocessing, google-pasta, flatbuffers
Successfully installed flatbuffers-1.12 google-pasta-0.2.0 keras-preprocessing-1.1.2 tensorflow-estimator-2.3.0 wrapt-1.12.1`, then I got the error in the title. Any suggestions?

**Comment by mwidjaja1** [comment]
How sure are you that the Python/Pip/Conda you think you're using are one associated with an ARM Version of Python? You can double check by launching the Python Interpreter in your terminal, and then taking a look at Python in the Activity Monitor app. There should be a section where it returns what architecture Python is using. Since you're using the ARM TensorFlow, you'd want the ARM Python. Then backtrack to make sure you're using the Pip/Conda associated with that Python install. 

If this isn't it, I'd be out of ideas. This type of warning is one I got a lot in the beginning, and it's because I ran an Intel/Rosetta Python the whole time without realizing it

**Comment by oresttokovenko** [comment]
According to your instructions I am using ARM Python. How can I check if my Conda/Condaforge install is ARM or not?

<img width="844" alt="Screen Shot 2020-12-09 at 10 41 33 PM" src="https://user-images.githubusercontent.com/51058259/101726427-beb13f00-3a6f-11eb-824c-fe3193a390b3.png">

**Comment by mwidjaja1** [comment]
I would imagine it'd be in the same folder as that Python. So `which python` and `which pip` and `which conda` should be in similar directories.

And at risk of asking a dumb question, you are using Python3.8 right?

**Comment by mwidjaja1** [comment]
I'm not sure if this helps you either but Apple released a new version of TensorFlow that has a buggy installation script. I submitted a Pull Request to Apple at https://github.com/apple/tensorflow_macos/pull/63/commits/b5e9eeddc3bcad2e63eade7fa543a98fea27f6d4 which fixes their script so you can use Conda Environments. I also left a comment with how I got it working and proof that it does work.

Could you give that a try? Perhaps they fixed something along the way.

**Comment by oresttokovenko** [comment]
@mwidjaja1 I got it working by installing it through mini-forge! Thank you for your help!

**Comment by mwidjaja1** [comment]
Nice! Just to make sure (so I can better improve these notes), do you mean you tried installing Miniforge Python first and then installing Apple's Tensorflow in it?

**Comment by oresttokovenko** [comment]
Remarkably simple actually! I downloaded the arm64 MiniForge3 installer, ran it with `bash Miniforge3-MacOSX-arm64.sh`, then ran `/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/apple/tensorflow_macos/master/scripts/download_and_install.sh)"` and created a new environment upon install. That's all

**Comment by mwidjaja1** [comment]
Huh, interesting. So does that use the Miniforge Python, but just create a virtual environment (not a Conda environment)? I didn't even think about going down that route.
